<?php 

/** 
Fields Summary: 
- cartPriceRule [coreShopCartPriceRule]
- voucherCode [input]
- discountNet [coreShopMoney]
- discountGross [coreShopMoney]
*/ 


return Pimcore\Model\DataObject\Fieldcollection\Definition::__set_state(array(
   'dao' => NULL,
   'key' => 'CoreShopProposalCartPriceRuleItem',
   'parentClass' => 'CoreShop\\Component\\Order\\Model\\ProposalCartPriceRuleItem',
   'implementsInterfaces' => NULL,
   'title' => NULL,
   'group' => NULL,
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'labelWidth' => 100,
     'layout' => NULL,
     'border' => false,
     'name' => NULL,
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => NULL,
     'height' => NULL,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
         'fieldtype' => 'panel',
         'labelWidth' => 100,
         'layout' => NULL,
         'border' => false,
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => NULL,
         'width' => NULL,
         'height' => NULL,
         'collapsible' => false,
         'collapsed' => false,
         'bodyStyle' => NULL,
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          CoreShop\Bundle\OrderBundle\CoreExtension\CartPriceRule::__set_state(array(
             'fieldtype' => 'coreShopCartPriceRule',
             'phpdocType' => 'CoreShop\\Component\\Order\\Model\\CartPriceRule',
             'allowEmpty' => false,
             'options' => NULL,
             'width' => '',
             'defaultValue' => NULL,
             'optionsProviderClass' => NULL,
             'optionsProviderData' => NULL,
             'queryColumnType' => 'varchar',
             'columnType' => 'varchar',
             'columnLength' => 190,
             'dynamicOptions' => false,
             'name' => 'cartPriceRule',
             'title' => 'coreshop.cart_price_rule_item.price_rule',
             'tooltip' => '',
             'mandatory' => false,
             'noteditable' => false,
             'index' => false,
             'locked' => false,
             'style' => '',
             'permissions' => NULL,
             'datatype' => 'data',
             'relationType' => false,
             'invisible' => false,
             'visibleGridView' => false,
             'visibleSearch' => false,
             'defaultValueGenerator' => '',
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
             'fieldtype' => 'input',
             'width' => NULL,
             'defaultValue' => NULL,
             'queryColumnType' => 'varchar',
             'columnType' => 'varchar',
             'columnLength' => 190,
             'phpdocType' => 'string',
             'regex' => '',
             'unique' => NULL,
             'showCharCount' => NULL,
             'name' => 'voucherCode',
             'title' => 'coreshop.cart_price_rule_item.voucher_code',
             'tooltip' => '',
             'mandatory' => false,
             'noteditable' => false,
             'index' => false,
             'locked' => false,
             'style' => '',
             'permissions' => NULL,
             'datatype' => 'data',
             'relationType' => false,
             'invisible' => false,
             'visibleGridView' => false,
             'visibleSearch' => false,
             'defaultValueGenerator' => '',
          )),
          2 => 
          CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
             'fieldtype' => 'coreShopMoney',
             'width' => '',
             'defaultValue' => NULL,
             'phpdocType' => 'int',
             'minValue' => NULL,
             'maxValue' => NULL,
             'name' => 'discountNet',
             'title' => 'coreshop.cart_price_rule_item.discount_net',
             'tooltip' => '',
             'mandatory' => false,
             'noteditable' => false,
             'index' => false,
             'locked' => false,
             'style' => '',
             'permissions' => NULL,
             'datatype' => 'data',
             'relationType' => false,
             'invisible' => false,
             'visibleGridView' => false,
             'visibleSearch' => false,
          )),
          3 => 
          CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
             'fieldtype' => 'coreShopMoney',
             'width' => '',
             'defaultValue' => NULL,
             'phpdocType' => 'int',
             'minValue' => NULL,
             'maxValue' => NULL,
             'name' => 'discountGross',
             'title' => 'coreshop.cart_price_rule_item.discount_gross',
             'tooltip' => '',
             'mandatory' => false,
             'noteditable' => false,
             'index' => false,
             'locked' => false,
             'style' => '',
             'permissions' => NULL,
             'datatype' => 'data',
             'relationType' => false,
             'invisible' => false,
             'visibleGridView' => false,
             'visibleSearch' => false,
          )),
        ),
         'locked' => false,
         'icon' => NULL,
      )),
    ),
     'locked' => false,
     'icon' => NULL,
  )),
));
